Implement handling of date field differences for date components
skiptools/skip-foundation pull request #25
Opened 2024-10-14 08:20 UTC by shial4

This PR implements the missing logic for calculating date component differences between a date and an endDate in the DateComponents initializer. 
Previously, the initializer contained a fatalError for handling date field differences, which caused crashes when using certain date-based operations. This change resolves that issue and ensures correct behavior for date differences.

**Changes:**
Date Difference Calculation: The initializer now calculates differences between date and endDate for various components, including era, year, month, day, hour, minute, second, weekday, weekOfMonth, and weekOfYear.
Handling nil endDate: If endDate is not provided, the initializer simply extracts the component values from the given date.
Unsupported Fields: 
Fields unsupported by java.util.Calendar (e.g., nanosecond, quarter, yearForWeekOfYear) have been commented out for future handling.

**Testing**
Tests using my local app which previously was crashing. 

**Impact**
This fix resolves crashes caused by the unimplemented date field difference logic and ensures proper date handling across the application.

- [x] REQUIRED: I have [signed](https://github.com/skiptools/clabot-config/pull/15) the [Contributor Agreement](https://github.com/skiptools/clabot-config)
- [x] REQUIRED: I have tested my change locally with `swift test`
- [x] OPTIONAL: I have tested my change on an iOS simulator or device
- [x] OPTIONAL: I have tested my change on an Android emulator or device

2024-10-14 08:23 UTC, shial4 commented
> 1. `git config --list | grep email`

Added my missing email to GitHub account

2024-10-14 12:54 UTC, marcprux commented
This looks great, but can you drop a couple tests for the logic into https://github.com/skiptools/skip-foundation/blob/main/Tests/SkipFoundationTests/DateTime/TestCalendar.swift, so we can be sure that the SkipFoundation version behaves the same as CoreFoundation?

2024-10-15 06:59 UTC, shial4 commented
@marcprux 
Ok, Added some test also updated title & description as I've made all the changes here for the functionality that I missed to have my calendar component working correctly on Android

2024-10-15 13:43 UTC, shial4 commented
Ok, I think Now I'm down. Went tru few iteration but it does match Swift now
Although, when I test there is few unrelated test failures in code not  not related to this change, I think.

2024-10-15 14:13 UTC, marcprux commented
> Although, when I test there is few unrelated test failures in code not not related to this change, I think.

The `TestCalendar.testTimeZoneDates`, `TestCalendar.testCalendarWithIdentifier`, and `TestCalendar.testDatesInCESTTimeZone` [failures](https://github.com/skiptools/skip-foundation/actions/runs/11347346665/job/31558510322#step:9:21014) are new. Do those fail for you when you run the SkipFoundation tests locally (i.e., against macOS and Robolectric)?

2024-10-15 18:54 UTC, marcprux requested changes
Looks great overall! Just a couple of review comments and a passing CI run and this can get merged.

2024-10-15 22:58 UTC, shial4 commented on Sources/SkipFoundation/Calendar.swift
> -        return Date(platformValue: components.createCalendarComponents(timeZone: self.timeZone).getTime())
Yea, Can't remember why I did it. Probably copy paste from my file I had before going into skip-foundation.
Restored, tough. Good catch :)

2024-10-15 22:59 UTC, shial4 commented on Sources/SkipFoundation/DateComponents.swift
> +        if components?.contains(.timeZone) == true {
updated

2024-10-15 23:04 UTC, shial4 commented
> > Although, when I test there is few unrelated test failures in code not not related to this change, I think.
> 
> The `TestCalendar.testTimeZoneDates`, `TestCalendar.testCalendarWithIdentifier`, and `TestCalendar.testDatesInCESTTimeZone` [failures](https://github.com/skiptools/skip-foundation/actions/runs/11347346665/job/31558510322#step:9:21014) are new. Do those fail for you when you run the SkipFoundation tests locally (i.e., against macOS and Robolectric)?

Regarding the test. 
only `testCalendarWithIdentifier` fails for me with
`java.lang.AssertionError: gregorian != iso8601`

2024-10-15 23:09 UTC, marcprux commented
> only `testCalendarWithIdentifier` fails for me with
> `java.lang.AssertionError: gregorian != iso8601`

Looks good. I think that assertion can be disabled, because we don't support any calendar other than Gregorian yet. Feel free to just remove the assertion.

2024-10-15 23:18 UTC, shial4 commented
> > only `testCalendarWithIdentifier` fails for me with
> > `java.lang.AssertionError: gregorian != iso8601`
> 
> Looks good. I think that assertion can be disabled, because we don't support any calendar other than Gregorian yet. Feel free to just remove the assertion.

done, deal

2024-10-15 23:36 UTC, marcprux approved these changes

2024-10-15 23:49 UTC, merged

2024-10-15 23:49 UTC, marcprux commented
Tests all pass. Thanks for the contribution!